### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by ghost** [mitmul/ssai#3]
Hello @mitmul. First of all, I appreciate sharing this great code and project!
For my research, I am trying to extract some features from your trained network.
However, I found out that there is no pre-trained model (or saved snapshot) that was trained with your dataset in this repo.
Instead of training from scratch with your network definition and dataset, would it be possible to ask for sharing the pre-trained model that you used in these slides (http://www.slideshare.net/mitmul/building-and-road-detection-from-large-aerial-imagery/1)?
Thank you for your time!

**Comment by jenifferYingyiWu** [comment]
I have review "https://github.com/mitmul/ssai/blob/master/scripts/test_evaluation.py", there are some codes about "precision" and "recall".
    But, how to implement getting the  "precision" and "recall" from the val.txt file (which has been tested by Caffe model).
    And, I cannot find "val.txt" in test_evaluation.py script.
    So, how to get  the  "precision" and "recall" from "val.txt"?

**Comment by mitmul** [comment]
@jenifferYingyiWu Thank you for checking my codes here. But this repo has been deprecated because whole things are re-implemented by using Chainer and I did refactoring for many codes.
So please check this newer version: https://github.com/mitmul/ssai-cnn
Well, now I'm preparing for pre-trained models and will update soon.

**Comment by mitmul** [comment]
@jenifferYingyiWu I uploaded pre-trained models here:
https://github.com/mitmul/ssai-cnn/wiki/Pre-trained-models
Please check it out!
